# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_project_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True),
        ),
    ]
